#My Experience using SQL 
#All queries are using the classicmodels schema from MySQL Workbench

#Report those payments greater than $100,000

Select * From classicmodels.`payments`
Where amount > 100000
order by amount desc

#Find the names for the sales reps for each customer

Select customerName, salesRepEmployeeNumber, employees.firstName, employees.lastName from classicmodels.`customers`
join classicmodels.`employees` ON customers.salesRepEmployeeNumber=employees.employeeNumber


#Which orders have a value greater than $5,000?

Select * , (quantityOrdered*priceEach) as TotalOrderPrice From classicmodels.`orderdetails`
Where (quantityOrdered*priceEach) > 5000


#Report the number of orders 'On Hold' for each customer.

Select customerName, Count(orders.status) From classicmodels.`customers`
Join classicmodels.`orders` On orders.customerNumber=customers.customerNumber
Where orders.status = "On Hold"
Group by customerName


#Market Basket Analysis: Find the products that are in the same order together more than ten times 

Select A.productCode, B.productCode, C.productName as productName1, D.productName as productName2, count(*) as totalcount from classicmodels.`orderdetails` as A
join classicmodels.`orderdetails` as B On A.orderNumber=B.orderNumber
join classicmodels.`products` as C On A.productCode=C.productCode
join classicmodels.`products` as D ON B.productCode=D.productCode
and A.productCode<>B.productCode
and B.productCode > A.productCode
group by A.productCode, B.productCode
order by totalcount desc

#Compute the revenue generated by each customer based on their orders. Also, show each customer's revenue as a percentage of total revenue. Sort by customer name.

Select A.customerName, A.customerNumber, sum(B.amount), sum(B.amount/8853839.23)*100  AS PercentageofRevenue From classicmodels.`customers` as A
Join classicmodels.`payments` as B ON A.customerNumber=B.customerNumber
group by customerName

#Tableau Dashboard
<div class='tableauPlaceholder' id='viz1722736654129' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Cl&#47;ClassicModelRevenuebyCustomerBreakdown&#47;Dashboard1&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='ClassicModelRevenuebyCustomerBreakdown&#47;Dashboard1' /><param name='tabs' value='yes' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Cl&#47;ClassicModelRevenuebyCustomerBreakdown&#47;Dashboard1&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1722736654129');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.minWidth='1000px';vizElement.style.maxWidth='100%';vizElement.style.minHeight='850px';vizElement.style.maxHeight=(divElement.offsetWidth*0.75)+'px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.minWidth='1000px';vizElement.style.maxWidth='100%';vizElement.style.minHeight='850px';vizElement.style.maxHeight=(divElement.offsetWidth*0.75)+'px';} else { vizElement.style.width='100%';vizElement.style.minHeight='750px';vizElement.style.maxHeight=(divElement.offsetWidth*1.77)+'px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
